//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotOR2RandoConsole.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Items : global::System.Configuration.ApplicationSettingsBase {
        
        private static Items defaultInstance = ((Items)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Items())));
        
        public static Items Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeArmbands {
            get {
                return ((int)(this["RandomizeArmbands"]));
            }
            set {
                this["RandomizeArmbands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeArmor {
            get {
                return ((int)(this["RandomizeArmor"]));
            }
            set {
                this["RandomizeArmor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeBelts {
            get {
                return ((int)(this["RandomizeBelts"]));
            }
            set {
                this["RandomizeBelts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeBlasters {
            get {
                return ((int)(this["RandomizeBlasters"]));
            }
            set {
                this["RandomizeBlasters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeHides {
            get {
                return ((int)(this["RandomizeHides"]));
            }
            set {
                this["RandomizeHides"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeCreature {
            get {
                return ((int)(this["RandomizeCreature"]));
            }
            set {
                this["RandomizeCreature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeDroid {
            get {
                return ((int)(this["RandomizeDroid"]));
            }
            set {
                this["RandomizeDroid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeGloves {
            get {
                return ((int)(this["RandomizeGloves"]));
            }
            set {
                this["RandomizeGloves"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeGrenades {
            get {
                return ((int)(this["RandomizeGrenades"]));
            }
            set {
                this["RandomizeGrenades"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeImplants {
            get {
                return ((int)(this["RandomizeImplants"]));
            }
            set {
                this["RandomizeImplants"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeLightsabers {
            get {
                return ((int)(this["RandomizeLightsabers"]));
            }
            set {
                this["RandomizeLightsabers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeMask {
            get {
                return ((int)(this["RandomizeMask"]));
            }
            set {
                this["RandomizeMask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeMelee {
            get {
                return ((int)(this["RandomizeMelee"]));
            }
            set {
                this["RandomizeMelee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeMines {
            get {
                return ((int)(this["RandomizeMines"]));
            }
            set {
                this["RandomizeMines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizePaz {
            get {
                return ((int)(this["RandomizePaz"]));
            }
            set {
                this["RandomizePaz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeStims {
            get {
                return ((int)(this["RandomizeStims"]));
            }
            set {
                this["RandomizeStims"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeUpgrade {
            get {
                return ((int)(this["RandomizeUpgrade"]));
            }
            set {
                this["RandomizeUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeVarious {
            get {
                return ((int)(this["RandomizeVarious"]));
            }
            set {
                this["RandomizeVarious"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizeProps {
            get {
                return ((int)(this["RandomizeProps"]));
            }
            set {
                this["RandomizeProps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomizePCrystal {
            get {
                return ((int)(this["RandomizePCrystal"]));
            }
            set {
                this["RandomizePCrystal"] = value;
            }
        }
    }
}
