//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotOR2RandoConsole.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Texture : global::System.Configuration.ApplicationSettingsBase {
        
        private static Texture defaultInstance = ((Texture)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Texture())));
        
        public static Texture Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TexturePack {
            get {
                return ((int)(this["TexturePack"]));
            }
            set {
                this["TexturePack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeWeapons {
            get {
                return ((int)(this["TextureRandomizeWeapons"]));
            }
            set {
                this["TextureRandomizeWeapons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeVehicles {
            get {
                return ((int)(this["TextureRandomizeVehicles"]));
            }
            set {
                this["TextureRandomizeVehicles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeStunt {
            get {
                return ((int)(this["TextureRandomizeStunt"]));
            }
            set {
                this["TextureRandomizeStunt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizePlayHeads {
            get {
                return ((int)(this["TextureRandomizePlayHeads"]));
            }
            set {
                this["TextureRandomizePlayHeads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizePlayBodies {
            get {
                return ((int)(this["TextureRandomizePlayBodies"]));
            }
            set {
                this["TextureRandomizePlayBodies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizePlaceables {
            get {
                return ((int)(this["TextureRandomizePlaceables"]));
            }
            set {
                this["TextureRandomizePlaceables"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeParty {
            get {
                return ((int)(this["TextureRandomizeParty"]));
            }
            set {
                this["TextureRandomizeParty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeOther {
            get {
                return ((int)(this["TextureRandomizeOther"]));
            }
            set {
                this["TextureRandomizeOther"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeNPC {
            get {
                return ((int)(this["TextureRandomizeNPC"]));
            }
            set {
                this["TextureRandomizeNPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeItems {
            get {
                return ((int)(this["TextureRandomizeItems"]));
            }
            set {
                this["TextureRandomizeItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeEffects {
            get {
                return ((int)(this["TextureRandomizeEffects"]));
            }
            set {
                this["TextureRandomizeEffects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeCubeMaps {
            get {
                return ((int)(this["TextureRandomizeCubeMaps"]));
            }
            set {
                this["TextureRandomizeCubeMaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeCreatures {
            get {
                return ((int)(this["TextureRandomizeCreatures"]));
            }
            set {
                this["TextureRandomizeCreatures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeEbonHawk {
            get {
                return ((int)(this["TextureRandomizeEbonHawk"]));
            }
            set {
                this["TextureRandomizeEbonHawk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeDantooine {
            get {
                return ((int)(this["TextureRandomizeDantooine"]));
            }
            set {
                this["TextureRandomizeDantooine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeM4_78 {
            get {
                return ((int)(this["TextureRandomizeM4_78"]));
            }
            set {
                this["TextureRandomizeM4_78"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeDxun {
            get {
                return ((int)(this["TextureRandomizeDxun"]));
            }
            set {
                this["TextureRandomizeDxun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeTelos {
            get {
                return ((int)(this["TextureRandomizeTelos"]));
            }
            set {
                this["TextureRandomizeTelos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizePeragus {
            get {
                return ((int)(this["TextureRandomizePeragus"]));
            }
            set {
                this["TextureRandomizePeragus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeOnderon {
            get {
                return ((int)(this["TextureRandomizeOnderon"]));
            }
            set {
                this["TextureRandomizeOnderon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeRavager {
            get {
                return ((int)(this["TextureRandomizeRavager"]));
            }
            set {
                this["TextureRandomizeRavager"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeNarShadaa {
            get {
                return ((int)(this["TextureRandomizeNarShadaa"]));
            }
            set {
                this["TextureRandomizeNarShadaa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeMiniGame {
            get {
                return ((int)(this["TextureRandomizeMiniGame"]));
            }
            set {
                this["TextureRandomizeMiniGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeMalachor {
            get {
                return ((int)(this["TextureRandomizeMalachor"]));
            }
            set {
                this["TextureRandomizeMalachor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeKorriban {
            get {
                return ((int)(this["TextureRandomizeKorriban"]));
            }
            set {
                this["TextureRandomizeKorriban"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextureRandomizeHarbinger {
            get {
                return ((int)(this["TextureRandomizeHarbinger"]));
            }
            set {
                this["TextureRandomizeHarbinger"] = value;
            }
        }
    }
}
